name: Build GPSMasterPatch

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          brew install ldid make xz
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Setup iOS SDK
        run: |
          mkdir -p ~/theos/sdks
          cd ~/theos/sdks
          curl -LO https://github.com/theos/sdks/releases/download/2024-08-26/iPhoneOS17.5.sdk.tar.xz
          tar -xJf iPhoneOS17.5.sdk.tar.xz
          ls -la

      - name: Build Package
        run: |
          export THEOS=~/theos
          export PATH="$THEOS/bin:$PATH"
          gmake package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GPSMasterPatch-deb
          path: packages/*.deb
